bulb:
  bulbs:
    nightstand: 192.168.0.240
    sleepingroom: 192.168.0.241
    livingroom: 192.168.0.242
    kitchen: 192.168.0.243
    corridor: 192.168.0.244
  masterBulb: corridor
serve:
  port: 8090
schedule:
  db:
    path: ./sqlite.db
location:
  lat: 50.273399
  lon: 18.648058
